runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: app.app


libraries:
- name: MySQLdb
  version: "latest"
- name: flask
  version: "latest"